### ISSUE TITLE
BTCCrackerDBContext Setup

### ISSUE THREAD

**Issue by jgric2** [mmcc1/BitcoinECDSA#1]
Hi there,
What are the details for the SQL server settings for BTCCrackerDBContext?

it keeps crashing on line 167 "rowCountsPerByte[0] = btcDB.WeightLogs.Count(x => x.Byte0 >= prob);"
as the server is not configured.

Please provide details to set up a local server for this :)

Thanks

**Comment by mmcc1** [comment]
The DAL makes use of Entity Framework.  You can point it at an SQL server and empty database on this line:

https://github.com/mmcc1/BitcoinECDSA/blob/4eb836587ac86b8ad233a842a162fad13e05e761/BTCECDSACracker/DAL/BTCCrackerDBContext.cs#L12

Then just Add Migration in Entity Framework to create the DB.
