### ISSUE TITLE
can it really break ecdsa?

### ISSUE THREAD

**Issue by sergeibystrov** [mmcc1/BitcoinECDSA#2]
does this actually breaks the address to give you the private key?
i don't see what part of code does that. can you please point me where in the code is the actual algorithm for that

**Comment by mmcc1** [comment]
Its more a set of approaches which weaken the effective key strength.   Its certainly not a break, but it does teach newer machine learning approaches to code breaking.

**Comment by sergeibystrov** [comment]
Your issue raised with our team has now been closed as it has being
unanswered for long so we deem it to be satisfactory
